server:
  port: 8888

spring:
  application:
    name: LuditoTestProject
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/migrations.sql

  security:
    user:
      name: mardon
      password: mardon
      roles: USER

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
